version: '3.7'
services: 
    node:
        image: node
        build: .
        ports: 
            - ${PORT}:${PORT}
        depends_on:
            - postgres
        restart: always
        environment: 
            - PORT:${PORT}
        volumes: 
            - ./logs:/usr/app/src/logs
            - ./src:/usr/app/src
        networks: 
            - network-bridge
    postgres: 
        image: postgres
        build: ./database
        restart: on-failure
        ports: 
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_PORT: ${POSTGRES_PORT}
            POSTGRES_DB: ${POSTGRES_DB}
        networks: 
            - network-bridge
networks: 
    network-bridge:
        external: true